### ISSUE TITLE
libsodium is not installed

### ISSUE THREAD

**Issue by brunobellmann** [charonn0/RB-libsodium#5]
Hey guys,
the `System.IsFunctionAvailable` returns `false`.

`libsodium` is surely installed in `/usr/local/lib`, did the instructions on https://libsodium.gitbook.io/doc/installation. (macOS)

What did i wrong?
Thank you

**Comment by charonn0** [comment]
Try changing the `libsodium.sodium` constant for macOS from "libsodium.dylib" to "/usr/local/lib/libsodium.dylib".

**Comment by brunobellmann** [comment]
Hello,
thanks for the answer but it didnt work out. I got this error message in Xojo.

![CleanShot 2021-08-11 at 13 58 47](https://user-images.githubusercontent.com/33653881/129024984-569ed509-b152-4ff6-a817-0cd89513ab58.png)

Thanks for your time

**Comment by charonn0** [comment]
I think I might have figured it out. Please revert any changes to the `libsodium.sodium` constant and then modify the `libsodium.IsAvailable()` method as follows. 

Change this line:
```xojo
  If Not available Then available = System.IsFunctionAvailable("sodium_init", "libsodium")
```
to look like this:
```xojo
  If Not available Then available = System.IsFunctionAvailable("sodium_init", sodium)
```

Basically, `IsAvailable()` is using the string `"libsodium"` instead of the platform-specific value found in the `sodium` constant. If I'm right that should clear up the problem, and if not try changing the `sodium` constant again as before.

**Comment by brunobellmann** [comment]
thank you! this solved my problem!

have a nice day
