### ISSUE TITLE
Possibility to generate a hash with an hard-coded Salt-Key (Argon2i)

### ISSUE THREAD

**Issue by brunobellmann** [charonn0/RB-libsodium#6]
Hello again,
is there a way to generate a Argon2-Hash with an hard-coded Salt-key?
I saw the `.DeriveKey` Method, but i think this is not the right way. The `.GenerateHash` doesnt care about the Salt-key.

Thanks for your time.

**Comment by charonn0** [comment]
> I saw the `.DeriveKey` Method, but i think this is not the right way. 

Actually it is. Generating a hash and deriving a key are functionally the same operation, just being used for different purposes.

`.GenerateHash` generates a fixed-length hash in an encoded form that is understood by `.VerifyHash`. This is the appropriate way to store a password (e.g. in a database). `.DeriveKey` generates a variable-length hash in raw binary form, which (if of the correct length) is suitable to be used as a cryptographic key. 

That said I would be remiss not to caution you that it is _not safe_ to re-use a salt when hashing passwords for storage. That's why the GenerateHash method doesn't give you the option.

**Comment by brunobellmann** [comment]
Yeah i thought this already.

Thank you.
